// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: academic_years.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAcademicYear = `-- name: CreateAcademicYear :one
INSERT INTO academic_years (year, is_active, class_days, enrollment_starts_at, enrollment_ends_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, year, is_active, class_days, enrollment_starts_at, enrollment_ends_at
`

type CreateAcademicYearParams struct {
	Year               int32       `json:"year"`
	IsActive           bool        `json:"is_active"`
	ClassDays          []int32     `json:"class_days"`
	EnrollmentStartsAt pgtype.Date `json:"enrollment_starts_at"`
	EnrollmentEndsAt   pgtype.Date `json:"enrollment_ends_at"`
}

func (q *Queries) CreateAcademicYear(ctx context.Context, arg CreateAcademicYearParams) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, createAcademicYear,
		arg.Year,
		arg.IsActive,
		arg.ClassDays,
		arg.EnrollmentStartsAt,
		arg.EnrollmentEndsAt,
	)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.IsActive,
		&i.ClassDays,
		&i.EnrollmentStartsAt,
		&i.EnrollmentEndsAt,
	)
	return i, err
}

const deleteAcademicYear = `-- name: DeleteAcademicYear :execrows
DELETE FROM academic_years WHERE id = $1
`

func (q *Queries) DeleteAcademicYear(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAcademicYear, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAcademicYear = `-- name: GetAcademicYear :one
SELECT id, year, is_active, class_days, enrollment_starts_at, enrollment_ends_at FROM academic_years WHERE id = $1
`

func (q *Queries) GetAcademicYear(ctx context.Context, id pgtype.UUID) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, getAcademicYear, id)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.IsActive,
		&i.ClassDays,
		&i.EnrollmentStartsAt,
		&i.EnrollmentEndsAt,
	)
	return i, err
}

const listAcademicYears = `-- name: ListAcademicYears :many
SELECT id, year, is_active, class_days, enrollment_starts_at, enrollment_ends_at FROM academic_years ORDER BY year DESC
`

func (q *Queries) ListAcademicYears(ctx context.Context) ([]AcademicYear, error) {
	rows, err := q.db.Query(ctx, listAcademicYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicYear{}
	for rows.Next() {
		var i AcademicYear
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.IsActive,
			&i.ClassDays,
			&i.EnrollmentStartsAt,
			&i.EnrollmentEndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAcademicYear = `-- name: UpdateAcademicYear :one
UPDATE academic_years SET
    is_active            = COALESCE($1, is_active),
    class_days           = COALESCE($2::int[], class_days),
    enrollment_starts_at = CASE WHEN $3::boolean
                                THEN $4::date
                                ELSE enrollment_starts_at END,
    enrollment_ends_at   = CASE WHEN $3::boolean
                                THEN $5::date
                                ELSE enrollment_ends_at END
WHERE id = $6
RETURNING id, year, is_active, class_days, enrollment_starts_at, enrollment_ends_at
`

type UpdateAcademicYearParams struct {
	IsActive           *bool       `json:"is_active"`
	ClassDays          []int32     `json:"class_days"`
	SetEnrollment      bool        `json:"set_enrollment"`
	EnrollmentStartsAt pgtype.Date `json:"enrollment_starts_at"`
	EnrollmentEndsAt   pgtype.Date `json:"enrollment_ends_at"`
	ID                 pgtype.UUID `json:"id"`
}

// Partial update: is_active and class_days fall back to current values when the
// caller omits them (COALESCE over a NULL narg). Enrollment dates are touched
// only when set_enrollment is true, which lets the caller set them to NULL
// explicitly without COALESCE swallowing the NULL.
func (q *Queries) UpdateAcademicYear(ctx context.Context, arg UpdateAcademicYearParams) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, updateAcademicYear,
		arg.IsActive,
		arg.ClassDays,
		arg.SetEnrollment,
		arg.EnrollmentStartsAt,
		arg.EnrollmentEndsAt,
		arg.ID,
	)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.IsActive,
		&i.ClassDays,
		&i.EnrollmentStartsAt,
		&i.EnrollmentEndsAt,
	)
	return i, err
}
