// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAttendanceRecords = `-- name: InsertAttendanceRecords :exec
INSERT INTO attendance_records (session_id, student_id, present)
SELECT $1, unnest($2::uuid[]), unnest($3::boolean[])
ON CONFLICT (session_id, student_id) DO NOTHING
`

type InsertAttendanceRecordsParams struct {
	SessionID pgtype.UUID   `json:"session_id"`
	Column2   []pgtype.UUID `json:"column_2"`
	Column3   []bool        `json:"column_3"`
}

// Bulk-insert a session's records. ON CONFLICT(session_id,student_id) DO NOTHING
// makes duplicate students within a payload (or a partial re-send) a no-op.
func (q *Queries) InsertAttendanceRecords(ctx context.Context, arg InsertAttendanceRecordsParams) error {
	_, err := q.db.Exec(ctx, insertAttendanceRecords, arg.SessionID, arg.Column2, arg.Column3)
	return err
}

const isScheduledDate = `-- name: IsScheduledDate :one
SELECT EXISTS (
    SELECT 1
    FROM classes c
    JOIN class_dates cd ON cd.academic_year_id = c.academic_year_id
    WHERE c.id = $1 AND cd.date = $2
) AS scheduled
`

type IsScheduledDateParams struct {
	ID   pgtype.UUID `json:"id"`
	Date pgtype.Date `json:"date"`
}

// True when the date is a scheduled class date for the class's academic year.
// Returns false for an unknown class OR an unscheduled date, so the sync loop
// marks both as skipped (parity with the old route, where an unknown class fell
// through to a failing FK insert that was also counted as skipped).
func (q *Queries) IsScheduledDate(ctx context.Context, arg IsScheduledDateParams) (bool, error) {
	row := q.db.QueryRow(ctx, isScheduledDate, arg.ID, arg.Date)
	var scheduled bool
	err := row.Scan(&scheduled)
	return scheduled, err
}

const listAttendanceRecordsForSessions = `-- name: ListAttendanceRecordsForSessions :many
SELECT id, session_id, student_id, present
FROM attendance_records
WHERE session_id = ANY($1::uuid[])
ORDER BY id
`

// Records of the given sessions, used to embed each session's records in the GET
// response after the scoped session list is fetched.
func (q *Queries) ListAttendanceRecordsForSessions(ctx context.Context, dollar_1 []pgtype.UUID) ([]AttendanceRecord, error) {
	rows, err := q.db.Query(ctx, listAttendanceRecordsForSessions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceRecord{}
	for rows.Next() {
		var i AttendanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StudentID,
			&i.Present,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceSessions = `-- name: ListAttendanceSessions :many
SELECT s.id, s.class_id, s.date, s.catechist_id, s.synced_at
FROM attendance_sessions s
WHERE ($1::uuid IS NULL OR s.class_id = $1)
  AND ($2::date IS NULL OR s.date >= $2)
  AND ($3::date IS NULL OR s.date <= $3)
  AND (
    $4::boolean
    OR EXISTS (
      SELECT 1 FROM class_catechists cc
      WHERE cc.class_id = s.class_id AND cc.catechist_id = $5
    )
  )
ORDER BY s.date DESC, s.id
`

type ListAttendanceSessionsParams struct {
	ClassID      pgtype.UUID `json:"class_id"`
	FromDate     pgtype.Date `json:"from_date"`
	ToDate       pgtype.Date `json:"to_date"`
	IsPrivileged bool        `json:"is_privileged"`
	ViewerID     pgtype.UUID `json:"viewer_id"`
}

// Sessions visible to the caller, newest first, with optional classId/from/to
// filters. Read scope replaces RLS: privileged roles (coordinator/admin) see every
// session; a catechist sees only sessions of classes they are assigned to.
func (q *Queries) ListAttendanceSessions(ctx context.Context, arg ListAttendanceSessionsParams) ([]AttendanceSession, error) {
	rows, err := q.db.Query(ctx, listAttendanceSessions,
		arg.ClassID,
		arg.FromDate,
		arg.ToDate,
		arg.IsPrivileged,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceSession{}
	for rows.Next() {
		var i AttendanceSession
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.Date,
			&i.CatechistID,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttendanceSession = `-- name: UpsertAttendanceSession :one
INSERT INTO attendance_sessions (class_id, date, catechist_id, synced_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (class_id, date) DO NOTHING
RETURNING id
`

type UpsertAttendanceSessionParams struct {
	ClassID     pgtype.UUID `json:"class_id"`
	Date        pgtype.Date `json:"date"`
	CatechistID pgtype.UUID `json:"catechist_id"`
}

// Idempotent session insert keyed on UNIQUE(class_id,date). On a re-sent batch the
// conflict triggers DO NOTHING, so RETURNING yields no row (pgx.ErrNoRows) — the
// caller treats that as "already synced" and skips. catechist_id comes from the
// token, never the client payload.
func (q *Queries) UpsertAttendanceSession(ctx context.Context, arg UpsertAttendanceSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertAttendanceSession, arg.ClassID, arg.Date, arg.CatechistID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
