// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authz.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isClassCatechist = `-- name: IsClassCatechist :one
SELECT EXISTS (
    SELECT 1 FROM class_catechists
    WHERE class_id = $1 AND catechist_id = $2
) AS is_member
`

type IsClassCatechistParams struct {
	ClassID     pgtype.UUID `json:"class_id"`
	CatechistID pgtype.UUID `json:"catechist_id"`
}

// Fine-grained authz check replacing Supabase RLS private.is_class_catechist():
// true when the catechist is assigned to the class via class_catechists.
func (q *Queries) IsClassCatechist(ctx context.Context, arg IsClassCatechistParams) (bool, error) {
	row := q.db.QueryRow(ctx, isClassCatechist, arg.ClassID, arg.CatechistID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}
