// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: class_dates.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkInsertClassDates = `-- name: BulkInsertClassDates :exec
INSERT INTO class_dates (academic_year_id, date)
SELECT $1, unnest($2::date[])
`

type BulkInsertClassDatesParams struct {
	AcademicYearID pgtype.UUID   `json:"academic_year_id"`
	Column2        []pgtype.Date `json:"column_2"`
}

// Bulk replace insert. Still fires the per-row trigger (defense in depth).
func (q *Queries) BulkInsertClassDates(ctx context.Context, arg BulkInsertClassDatesParams) error {
	_, err := q.db.Exec(ctx, bulkInsertClassDates, arg.AcademicYearID, arg.Column2)
	return err
}

const deleteClassDatesForYear = `-- name: DeleteClassDatesForYear :exec
DELETE FROM class_dates WHERE academic_year_id = $1
`

func (q *Queries) DeleteClassDatesForYear(ctx context.Context, academicYearID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClassDatesForYear, academicYearID)
	return err
}

const getClassDays = `-- name: GetClassDays :one
SELECT class_days FROM academic_years WHERE id = $1
`

// Allowed class weekdays of the year, used to validate each submitted date in Go
// (the trigger validate_class_date_day re-checks in the DB). No rows → unknown year.
func (q *Queries) GetClassDays(ctx context.Context, id pgtype.UUID) ([]int32, error) {
	row := q.db.QueryRow(ctx, getClassDays, id)
	var class_days []int32
	err := row.Scan(&class_days)
	return class_days, err
}

const listClassDates = `-- name: ListClassDates :many
SELECT date FROM class_dates WHERE academic_year_id = $1 ORDER BY date
`

// Scheduled dates of the academic year, ordered chronologically.
func (q *Queries) ListClassDates(ctx context.Context, academicYearID pgtype.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listClassDates, academicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var date pgtype.Date
		if err := rows.Scan(&date); err != nil {
			return nil, err
		}
		items = append(items, date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLockedDates = `-- name: ListLockedDates :many
SELECT DISTINCT s.date
FROM attendance_sessions s
JOIN classes c ON c.id = s.class_id
WHERE c.academic_year_id = $1
ORDER BY s.date
`

// "Locked" dates: those that already have an attendance session for any class in
// the year. Removing one of these from the calendar is blocked (would orphan a
// recorded chamada). DISTINCT because several classes can share a date.
func (q *Queries) ListLockedDates(ctx context.Context, academicYearID pgtype.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listLockedDates, academicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var date pgtype.Date
		if err := rows.Scan(&date); err != nil {
			return nil, err
		}
		items = append(items, date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
