// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addClassCatechist = `-- name: AddClassCatechist :exec
INSERT INTO class_catechists (class_id, catechist_id) VALUES ($1, $2)
`

type AddClassCatechistParams struct {
	ClassID     pgtype.UUID `json:"class_id"`
	CatechistID pgtype.UUID `json:"catechist_id"`
}

func (q *Queries) AddClassCatechist(ctx context.Context, arg AddClassCatechistParams) error {
	_, err := q.db.Exec(ctx, addClassCatechist, arg.ClassID, arg.CatechistID)
	return err
}

const createClass = `-- name: CreateClass :one
INSERT INTO classes (academic_year_id, name, level, schedule)
VALUES ($1, $2, $3, $4)
RETURNING id, academic_year_id, name, level, schedule, is_archived, created_at
`

type CreateClassParams struct {
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
	Name           string      `json:"name"`
	Level          *string     `json:"level"`
	Schedule       *string     `json:"schedule"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, createClass,
		arg.AcademicYearID,
		arg.Name,
		arg.Level,
		arg.Schedule,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.Name,
		&i.Level,
		&i.Schedule,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClassCatechists = `-- name: DeleteClassCatechists :exec
DELETE FROM class_catechists WHERE class_id = $1
`

func (q *Queries) DeleteClassCatechists(ctx context.Context, classID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClassCatechists, classID)
	return err
}

const getClass = `-- name: GetClass :one
SELECT id, academic_year_id, name, level, schedule, is_archived, created_at FROM classes WHERE id = $1
`

func (q *Queries) GetClass(ctx context.Context, id pgtype.UUID) (Class, error) {
	row := q.db.QueryRow(ctx, getClass, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.Name,
		&i.Level,
		&i.Schedule,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}

const listClassCatechistIDs = `-- name: ListClassCatechistIDs :many
SELECT catechist_id FROM class_catechists WHERE class_id = $1 ORDER BY catechist_id
`

func (q *Queries) ListClassCatechistIDs(ctx context.Context, classID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listClassCatechistIDs, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var catechist_id pgtype.UUID
		if err := rows.Scan(&catechist_id); err != nil {
			return nil, err
		}
		items = append(items, catechist_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClasses = `-- name: ListClasses :many
SELECT
    c.id, c.academic_year_id, c.name, c.level, c.schedule, c.is_archived, c.created_at,
    COALESCE(
        ARRAY_AGG(cc.catechist_id ORDER BY cc.catechist_id) FILTER (WHERE cc.catechist_id IS NOT NULL),
        '{}'
    )::uuid[] AS catechist_ids
FROM classes c
LEFT JOIN class_catechists cc ON cc.class_id = c.id
GROUP BY c.id
ORDER BY c.name
`

type ListClassesRow struct {
	ID             pgtype.UUID        `json:"id"`
	AcademicYearID pgtype.UUID        `json:"academic_year_id"`
	Name           string             `json:"name"`
	Level          *string            `json:"level"`
	Schedule       *string            `json:"schedule"`
	IsArchived     bool               `json:"is_archived"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CatechistIds   []pgtype.UUID      `json:"catechist_ids"`
}

// Coordinator/admin view: every class, with its assigned catechist ids aggregated
// so the SPA can render/edit assignments without an extra round-trip.
func (q *Queries) ListClasses(ctx context.Context) ([]ListClassesRow, error) {
	rows, err := q.db.Query(ctx, listClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassesRow{}
	for rows.Next() {
		var i ListClassesRow
		if err := rows.Scan(
			&i.ID,
			&i.AcademicYearID,
			&i.Name,
			&i.Level,
			&i.Schedule,
			&i.IsArchived,
			&i.CreatedAt,
			&i.CatechistIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesForCatechist = `-- name: ListClassesForCatechist :many
SELECT
    c.id, c.academic_year_id, c.name, c.level, c.schedule, c.is_archived, c.created_at,
    COALESCE(
        ARRAY_AGG(cc.catechist_id ORDER BY cc.catechist_id) FILTER (WHERE cc.catechist_id IS NOT NULL),
        '{}'
    )::uuid[] AS catechist_ids
FROM classes c
LEFT JOIN class_catechists cc ON cc.class_id = c.id
WHERE c.id IN (SELECT m.class_id FROM class_catechists m WHERE m.catechist_id = $1)
GROUP BY c.id
ORDER BY c.name
`

type ListClassesForCatechistRow struct {
	ID             pgtype.UUID        `json:"id"`
	AcademicYearID pgtype.UUID        `json:"academic_year_id"`
	Name           string             `json:"name"`
	Level          *string            `json:"level"`
	Schedule       *string            `json:"schedule"`
	IsArchived     bool               `json:"is_archived"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CatechistIds   []pgtype.UUID      `json:"catechist_ids"`
}

// Per-catechist scope replacing the old RLS: only classes the catechist is
// assigned to, still aggregating the full set of catechist ids for the class.
func (q *Queries) ListClassesForCatechist(ctx context.Context, catechistID pgtype.UUID) ([]ListClassesForCatechistRow, error) {
	rows, err := q.db.Query(ctx, listClassesForCatechist, catechistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassesForCatechistRow{}
	for rows.Next() {
		var i ListClassesForCatechistRow
		if err := rows.Scan(
			&i.ID,
			&i.AcademicYearID,
			&i.Name,
			&i.Level,
			&i.Schedule,
			&i.IsArchived,
			&i.CreatedAt,
			&i.CatechistIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByClass = `-- name: ListStudentsByClass :many
SELECT id, class_id, full_name, birth_date, city, first_communion, confirmation, previous_catechism, religious_books, guardian_father_name, guardian_mother_name, guardian_phone, guardian_email, is_active, created_at FROM students WHERE class_id = $1 AND is_active ORDER BY full_name
`

func (q *Queries) ListStudentsByClass(ctx context.Context, classID pgtype.UUID) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudentsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.FullName,
			&i.BirthDate,
			&i.City,
			&i.FirstCommunion,
			&i.Confirmation,
			&i.PreviousCatechism,
			&i.ReligiousBooks,
			&i.GuardianFatherName,
			&i.GuardianMotherName,
			&i.GuardianPhone,
			&i.GuardianEmail,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClass = `-- name: UpdateClass :one
UPDATE classes SET
    name             = COALESCE($1, name),
    academic_year_id = COALESCE($2::uuid, academic_year_id),
    level            = COALESCE($3, level),
    schedule         = COALESCE($4, schedule),
    is_archived      = COALESCE($5, is_archived)
WHERE id = $6
RETURNING id, academic_year_id, name, level, schedule, is_archived, created_at
`

type UpdateClassParams struct {
	Name           *string     `json:"name"`
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
	Level          *string     `json:"level"`
	Schedule       *string     `json:"schedule"`
	IsArchived     *bool       `json:"is_archived"`
	ID             pgtype.UUID `json:"id"`
}

// Partial update: every field falls back to its current value when the caller
// omits it (COALESCE over a NULL narg). Doubles as the row fetch, so a missing id
// returns no rows (→ 404). Catechist assignments are handled separately.
func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, updateClass,
		arg.Name,
		arg.AcademicYearID,
		arg.Level,
		arg.Schedule,
		arg.IsArchived,
		arg.ID,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.Name,
		&i.Level,
		&i.Schedule,
		&i.IsArchived,
		&i.CreatedAt,
	)
	return i, err
}
