// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveEnrollment = `-- name: ApproveEnrollment :one
UPDATE enrollments SET
    status              = 'approved',
    approved_student_id = $2,
    approved_class_id   = $3,
    reviewed_by         = $4,
    reviewed_at         = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, academic_year_id, status, full_name, birth_date, city, first_communion, confirmation, previous_catechism, religious_books, guardian_father_name, guardian_mother_name, guardian_phone, guardian_email, is_renewal, previous_name, rejection_reason, approved_class_id, approved_student_id, reviewed_by, reviewed_at, created_at
`

type ApproveEnrollmentParams struct {
	ID                pgtype.UUID `json:"id"`
	ApprovedStudentID pgtype.UUID `json:"approved_student_id"`
	ApprovedClassID   pgtype.UUID `json:"approved_class_id"`
	ReviewedBy        pgtype.UUID `json:"reviewed_by"`
}

// Marks an enrollment approved with the materialized student/class and the reviewer
// metadata. The status guard keeps the transition idempotent at the row level.
func (q *Queries) ApproveEnrollment(ctx context.Context, arg ApproveEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, approveEnrollment,
		arg.ID,
		arg.ApprovedStudentID,
		arg.ApprovedClassID,
		arg.ReviewedBy,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.Status,
		&i.FullName,
		&i.BirthDate,
		&i.City,
		&i.FirstCommunion,
		&i.Confirmation,
		&i.PreviousCatechism,
		&i.ReligiousBooks,
		&i.GuardianFatherName,
		&i.GuardianMotherName,
		&i.GuardianPhone,
		&i.GuardianEmail,
		&i.IsRenewal,
		&i.PreviousName,
		&i.RejectionReason,
		&i.ApprovedClassID,
		&i.ApprovedStudentID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (
    academic_year_id, full_name, birth_date, city, first_communion, confirmation,
    previous_catechism, religious_books, guardian_father_name, guardian_mother_name,
    guardian_phone, guardian_email, is_renewal, previous_name
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, academic_year_id, status, full_name, birth_date, city, first_communion, confirmation, previous_catechism, religious_books, guardian_father_name, guardian_mother_name, guardian_phone, guardian_email, is_renewal, previous_name, rejection_reason, approved_class_id, approved_student_id, reviewed_by, reviewed_at, created_at
`

type CreateEnrollmentParams struct {
	AcademicYearID     pgtype.UUID `json:"academic_year_id"`
	FullName           string      `json:"full_name"`
	BirthDate          pgtype.Date `json:"birth_date"`
	City               *string     `json:"city"`
	FirstCommunion     bool        `json:"first_communion"`
	Confirmation       bool        `json:"confirmation"`
	PreviousCatechism  *string     `json:"previous_catechism"`
	ReligiousBooks     *string     `json:"religious_books"`
	GuardianFatherName *string     `json:"guardian_father_name"`
	GuardianMotherName *string     `json:"guardian_mother_name"`
	GuardianPhone      *string     `json:"guardian_phone"`
	GuardianEmail      *string     `json:"guardian_email"`
	IsRenewal          bool        `json:"is_renewal"`
	PreviousName       *string     `json:"previous_name"`
}

// Public submission (privileged path, no auth — equivalent to the old service-role
// client). The academic_year_id is resolved server-side from the active year; status
// defaults to 'pending'.
func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.AcademicYearID,
		arg.FullName,
		arg.BirthDate,
		arg.City,
		arg.FirstCommunion,
		arg.Confirmation,
		arg.PreviousCatechism,
		arg.ReligiousBooks,
		arg.GuardianFatherName,
		arg.GuardianMotherName,
		arg.GuardianPhone,
		arg.GuardianEmail,
		arg.IsRenewal,
		arg.PreviousName,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.Status,
		&i.FullName,
		&i.BirthDate,
		&i.City,
		&i.FirstCommunion,
		&i.Confirmation,
		&i.PreviousCatechism,
		&i.ReligiousBooks,
		&i.GuardianFatherName,
		&i.GuardianMotherName,
		&i.GuardianPhone,
		&i.GuardianEmail,
		&i.IsRenewal,
		&i.PreviousName,
		&i.RejectionReason,
		&i.ApprovedClassID,
		&i.ApprovedStudentID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStudentFromEnrollment = `-- name: CreateStudentFromEnrollment :one
INSERT INTO students (
    class_id, full_name, birth_date, city, first_communion, confirmation,
    previous_catechism, religious_books, guardian_father_name,
    guardian_mother_name, guardian_phone, guardian_email
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type CreateStudentFromEnrollmentParams struct {
	ClassID            pgtype.UUID `json:"class_id"`
	FullName           string      `json:"full_name"`
	BirthDate          pgtype.Date `json:"birth_date"`
	City               *string     `json:"city"`
	FirstCommunion     bool        `json:"first_communion"`
	Confirmation       bool        `json:"confirmation"`
	PreviousCatechism  *string     `json:"previous_catechism"`
	ReligiousBooks     *string     `json:"religious_books"`
	GuardianFatherName *string     `json:"guardian_father_name"`
	GuardianMotherName *string     `json:"guardian_mother_name"`
	GuardianPhone      *string     `json:"guardian_phone"`
	GuardianEmail      *string     `json:"guardian_email"`
}

// Materializes a new student from an approved enrollment's fields, into the chosen
// class. Mirrors CreateStudent but is scoped to the approval transaction.
func (q *Queries) CreateStudentFromEnrollment(ctx context.Context, arg CreateStudentFromEnrollmentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createStudentFromEnrollment,
		arg.ClassID,
		arg.FullName,
		arg.BirthDate,
		arg.City,
		arg.FirstCommunion,
		arg.Confirmation,
		arg.PreviousCatechism,
		arg.ReligiousBooks,
		arg.GuardianFatherName,
		arg.GuardianMotherName,
		arg.GuardianPhone,
		arg.GuardianEmail,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getActiveEnrollmentYear = `-- name: GetActiveEnrollmentYear :one
SELECT id, enrollment_starts_at, enrollment_ends_at
FROM academic_years
WHERE is_active = TRUE
LIMIT 1
`

type GetActiveEnrollmentYearRow struct {
	ID                 pgtype.UUID `json:"id"`
	EnrollmentStartsAt pgtype.Date `json:"enrollment_starts_at"`
	EnrollmentEndsAt   pgtype.Date `json:"enrollment_ends_at"`
}

// The active academic year plus its enrollment window, used by the public submit
// to gate on the open period. No rows → there is no active year configured.
func (q *Queries) GetActiveEnrollmentYear(ctx context.Context) (GetActiveEnrollmentYearRow, error) {
	row := q.db.QueryRow(ctx, getActiveEnrollmentYear)
	var i GetActiveEnrollmentYearRow
	err := row.Scan(&i.ID, &i.EnrollmentStartsAt, &i.EnrollmentEndsAt)
	return i, err
}

const getEnrollmentForUpdate = `-- name: GetEnrollmentForUpdate :one
SELECT id, academic_year_id, status, full_name, birth_date, city, first_communion, confirmation, previous_catechism, religious_books, guardian_father_name, guardian_mother_name, guardian_phone, guardian_email, is_renewal, previous_name, rejection_reason, approved_class_id, approved_student_id, reviewed_by, reviewed_at, created_at FROM enrollments WHERE id = $1 FOR UPDATE
`

// Fetch a single enrollment and lock its row for the review transaction so the
// pending → approved/rejected transition cannot race. No rows → unknown id (404).
func (q *Queries) GetEnrollmentForUpdate(ctx context.Context, id pgtype.UUID) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentForUpdate, id)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.Status,
		&i.FullName,
		&i.BirthDate,
		&i.City,
		&i.FirstCommunion,
		&i.Confirmation,
		&i.PreviousCatechism,
		&i.ReligiousBooks,
		&i.GuardianFatherName,
		&i.GuardianMotherName,
		&i.GuardianPhone,
		&i.GuardianEmail,
		&i.IsRenewal,
		&i.PreviousName,
		&i.RejectionReason,
		&i.ApprovedClassID,
		&i.ApprovedStudentID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEnrollmentsByStatus = `-- name: ListEnrollmentsByStatus :many
SELECT id, academic_year_id, status, full_name, birth_date, city, first_communion, confirmation, previous_catechism, religious_books, guardian_father_name, guardian_mother_name, guardian_phone, guardian_email, is_renewal, previous_name, rejection_reason, approved_class_id, approved_student_id, reviewed_by, reviewed_at, created_at FROM enrollments
WHERE academic_year_id = $1
  AND status = $2
  AND ($3::text IS NULL OR full_name ILIKE '%' || $3::text || '%')
ORDER BY created_at DESC
`

type ListEnrollmentsByStatusParams struct {
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
	Status         string      `json:"status"`
	Q              *string     `json:"q"`
}

// Coordinator listing scoped to the active year, filtered by status and optionally
// by name (ILIKE). A NULL q returns every enrollment of that status; the same narg is
// referenced twice so sqlc emits a single nullable Q parameter.
func (q *Queries) ListEnrollmentsByStatus(ctx context.Context, arg ListEnrollmentsByStatusParams) ([]Enrollment, error) {
	rows, err := q.db.Query(ctx, listEnrollmentsByStatus, arg.AcademicYearID, arg.Status, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Enrollment{}
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.ID,
			&i.AcademicYearID,
			&i.Status,
			&i.FullName,
			&i.BirthDate,
			&i.City,
			&i.FirstCommunion,
			&i.Confirmation,
			&i.PreviousCatechism,
			&i.ReligiousBooks,
			&i.GuardianFatherName,
			&i.GuardianMotherName,
			&i.GuardianPhone,
			&i.GuardianEmail,
			&i.IsRenewal,
			&i.PreviousName,
			&i.RejectionReason,
			&i.ApprovedClassID,
			&i.ApprovedStudentID,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectEnrollment = `-- name: RejectEnrollment :one
UPDATE enrollments SET
    status           = 'rejected',
    rejection_reason = $2,
    reviewed_by      = $3,
    reviewed_at      = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, academic_year_id, status, full_name, birth_date, city, first_communion, confirmation, previous_catechism, religious_books, guardian_father_name, guardian_mother_name, guardian_phone, guardian_email, is_renewal, previous_name, rejection_reason, approved_class_id, approved_student_id, reviewed_by, reviewed_at, created_at
`

type RejectEnrollmentParams struct {
	ID              pgtype.UUID `json:"id"`
	RejectionReason *string     `json:"rejection_reason"`
	ReviewedBy      pgtype.UUID `json:"reviewed_by"`
}

// Marks an enrollment rejected with an optional reason and the reviewer. The status
// guard keeps the transition idempotent at the row level.
func (q *Queries) RejectEnrollment(ctx context.Context, arg RejectEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, rejectEnrollment, arg.ID, arg.RejectionReason, arg.ReviewedBy)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.Status,
		&i.FullName,
		&i.BirthDate,
		&i.City,
		&i.FirstCommunion,
		&i.Confirmation,
		&i.PreviousCatechism,
		&i.ReligiousBooks,
		&i.GuardianFatherName,
		&i.GuardianMotherName,
		&i.GuardianPhone,
		&i.GuardianEmail,
		&i.IsRenewal,
		&i.PreviousName,
		&i.RejectionReason,
		&i.ApprovedClassID,
		&i.ApprovedStudentID,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateStudentFromEnrollment = `-- name: UpdateStudentFromEnrollment :one
UPDATE students SET
    class_id             = $2,
    full_name            = $3,
    birth_date           = $4,
    city                 = $5,
    first_communion      = $6,
    confirmation         = $7,
    previous_catechism   = $8,
    religious_books      = $9,
    guardian_father_name = $10,
    guardian_mother_name = $11,
    guardian_phone       = $12,
    guardian_email       = $13
WHERE id = $1
RETURNING id
`

type UpdateStudentFromEnrollmentParams struct {
	ID                 pgtype.UUID `json:"id"`
	ClassID            pgtype.UUID `json:"class_id"`
	FullName           string      `json:"full_name"`
	BirthDate          pgtype.Date `json:"birth_date"`
	City               *string     `json:"city"`
	FirstCommunion     bool        `json:"first_communion"`
	Confirmation       bool        `json:"confirmation"`
	PreviousCatechism  *string     `json:"previous_catechism"`
	ReligiousBooks     *string     `json:"religious_books"`
	GuardianFatherName *string     `json:"guardian_father_name"`
	GuardianMotherName *string     `json:"guardian_mother_name"`
	GuardianPhone      *string     `json:"guardian_phone"`
	GuardianEmail      *string     `json:"guardian_email"`
}

// Overwrites an existing student (re-enrollment/renewal) with the enrollment's
// fields and (re)assigns the chosen class. Unlike the partial students update this
// writes every column unconditionally. No rows → unknown student id.
func (q *Queries) UpdateStudentFromEnrollment(ctx context.Context, arg UpdateStudentFromEnrollmentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateStudentFromEnrollment,
		arg.ID,
		arg.ClassID,
		arg.FullName,
		arg.BirthDate,
		arg.City,
		arg.FirstCommunion,
		arg.Confirmation,
		arg.PreviousCatechism,
		arg.ReligiousBooks,
		arg.GuardianFatherName,
		arg.GuardianMotherName,
		arg.GuardianPhone,
		arg.GuardianEmail,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
