// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcademicYear struct {
	ID                 pgtype.UUID `json:"id"`
	Year               int32       `json:"year"`
	IsActive           bool        `json:"is_active"`
	ClassDays          []int32     `json:"class_days"`
	EnrollmentStartsAt pgtype.Date `json:"enrollment_starts_at"`
	EnrollmentEndsAt   pgtype.Date `json:"enrollment_ends_at"`
}

type AttendanceRecord struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	StudentID pgtype.UUID `json:"student_id"`
	Present   bool        `json:"present"`
}

type AttendanceSession struct {
	ID          pgtype.UUID        `json:"id"`
	ClassID     pgtype.UUID        `json:"class_id"`
	Date        pgtype.Date        `json:"date"`
	CatechistID pgtype.UUID        `json:"catechist_id"`
	SyncedAt    pgtype.Timestamptz `json:"synced_at"`
}

type Class struct {
	ID             pgtype.UUID        `json:"id"`
	AcademicYearID pgtype.UUID        `json:"academic_year_id"`
	Name           string             `json:"name"`
	Level          *string            `json:"level"`
	Schedule       *string            `json:"schedule"`
	IsArchived     bool               `json:"is_archived"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ClassCatechist struct {
	ClassID     pgtype.UUID `json:"class_id"`
	CatechistID pgtype.UUID `json:"catechist_id"`
}

type ClassDate struct {
	ID             pgtype.UUID `json:"id"`
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
	Date           pgtype.Date `json:"date"`
}

type Enrollment struct {
	ID                 pgtype.UUID        `json:"id"`
	AcademicYearID     pgtype.UUID        `json:"academic_year_id"`
	Status             string             `json:"status"`
	FullName           string             `json:"full_name"`
	BirthDate          pgtype.Date        `json:"birth_date"`
	City               *string            `json:"city"`
	FirstCommunion     bool               `json:"first_communion"`
	Confirmation       bool               `json:"confirmation"`
	PreviousCatechism  *string            `json:"previous_catechism"`
	ReligiousBooks     *string            `json:"religious_books"`
	GuardianFatherName *string            `json:"guardian_father_name"`
	GuardianMotherName *string            `json:"guardian_mother_name"`
	GuardianPhone      *string            `json:"guardian_phone"`
	GuardianEmail      *string            `json:"guardian_email"`
	IsRenewal          bool               `json:"is_renewal"`
	PreviousName       *string            `json:"previous_name"`
	RejectionReason    *string            `json:"rejection_reason"`
	ApprovedClassID    pgtype.UUID        `json:"approved_class_id"`
	ApprovedStudentID  pgtype.UUID        `json:"approved_student_id"`
	ReviewedBy         pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt         pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID                 pgtype.UUID        `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	FullName           string             `json:"full_name"`
	Role               string             `json:"role"`
	IsActive           bool               `json:"is_active"`
	MustChangePassword bool               `json:"must_change_password"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Student struct {
	ID                 pgtype.UUID        `json:"id"`
	ClassID            pgtype.UUID        `json:"class_id"`
	FullName           string             `json:"full_name"`
	BirthDate          pgtype.Date        `json:"birth_date"`
	City               *string            `json:"city"`
	FirstCommunion     bool               `json:"first_communion"`
	Confirmation       bool               `json:"confirmation"`
	PreviousCatechism  *string            `json:"previous_catechism"`
	ReligiousBooks     *string            `json:"religious_books"`
	GuardianFatherName *string            `json:"guardian_father_name"`
	GuardianMotherName *string            `json:"guardian_mother_name"`
	GuardianPhone      *string            `json:"guardian_phone"`
	GuardianEmail      *string            `json:"guardian_email"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
