// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReportClass = `-- name: GetReportClass :one
SELECT name
FROM classes
WHERE id = $1
`

// Class label used in the attendance report header. A missing id returns no rows
// so the handler maps it through the normal 404 DB path.
func (q *Queries) GetReportClass(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getReportClass, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listReportRecords = `-- name: ListReportRecords :many
SELECT session_id, student_id, present
FROM attendance_records
WHERE session_id = ANY($1::uuid[])
ORDER BY session_id, student_id
`

type ListReportRecordsRow struct {
	SessionID pgtype.UUID `json:"session_id"`
	StudentID pgtype.UUID `json:"student_id"`
	Present   bool        `json:"present"`
}

// Presence records for the report sessions. The service skips this query when the
// period has no sessions.
func (q *Queries) ListReportRecords(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListReportRecordsRow, error) {
	rows, err := q.db.Query(ctx, listReportRecords, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportRecordsRow{}
	for rows.Next() {
		var i ListReportRecordsRow
		if err := rows.Scan(&i.SessionID, &i.StudentID, &i.Present); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportSessions = `-- name: ListReportSessions :many
SELECT id, date
FROM attendance_sessions
WHERE class_id = $1
  AND date >= $2
  AND date <= $3
ORDER BY date, id
`

type ListReportSessionsParams struct {
	ClassID  pgtype.UUID `json:"class_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type ListReportSessionsRow struct {
	ID   pgtype.UUID `json:"id"`
	Date pgtype.Date `json:"date"`
}

// Sessions for the requested class and inclusive date period, ordered oldest first
// to match the legacy PDF/XLSX column order.
func (q *Queries) ListReportSessions(ctx context.Context, arg ListReportSessionsParams) ([]ListReportSessionsRow, error) {
	rows, err := q.db.Query(ctx, listReportSessions, arg.ClassID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportSessionsRow{}
	for rows.Next() {
		var i ListReportSessionsRow
		if err := rows.Scan(&i.ID, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportStudents = `-- name: ListReportStudents :many
SELECT id, full_name
FROM students
WHERE class_id = $1
ORDER BY full_name
`

type ListReportStudentsRow struct {
	ID       pgtype.UUID `json:"id"`
	FullName string      `json:"full_name"`
}

// Preserve the legacy report payload shape: students are returned as id/full_name
// and ordered by name.
func (q *Queries) ListReportStudents(ctx context.Context, classID pgtype.UUID) ([]ListReportStudentsRow, error) {
	rows, err := q.db.Query(ctx, listReportStudents, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportStudentsRow{}
	for rows.Next() {
		var i ListReportStudentsRow
		if err := rows.Scan(&i.ID, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
