// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
    class_id, full_name, birth_date, city, first_communion, confirmation,
    previous_catechism, religious_books, guardian_father_name,
    guardian_mother_name, guardian_phone, guardian_email
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, class_id, full_name, birth_date, city, first_communion, confirmation, previous_catechism, religious_books, guardian_father_name, guardian_mother_name, guardian_phone, guardian_email, is_active, created_at
`

type CreateStudentParams struct {
	ClassID            pgtype.UUID `json:"class_id"`
	FullName           string      `json:"full_name"`
	BirthDate          pgtype.Date `json:"birth_date"`
	City               *string     `json:"city"`
	FirstCommunion     bool        `json:"first_communion"`
	Confirmation       bool        `json:"confirmation"`
	PreviousCatechism  *string     `json:"previous_catechism"`
	ReligiousBooks     *string     `json:"religious_books"`
	GuardianFatherName *string     `json:"guardian_father_name"`
	GuardianMotherName *string     `json:"guardian_mother_name"`
	GuardianPhone      *string     `json:"guardian_phone"`
	GuardianEmail      *string     `json:"guardian_email"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.ClassID,
		arg.FullName,
		arg.BirthDate,
		arg.City,
		arg.FirstCommunion,
		arg.Confirmation,
		arg.PreviousCatechism,
		arg.ReligiousBooks,
		arg.GuardianFatherName,
		arg.GuardianMotherName,
		arg.GuardianPhone,
		arg.GuardianEmail,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.FullName,
		&i.BirthDate,
		&i.City,
		&i.FirstCommunion,
		&i.Confirmation,
		&i.PreviousCatechism,
		&i.ReligiousBooks,
		&i.GuardianFatherName,
		&i.GuardianMotherName,
		&i.GuardianPhone,
		&i.GuardianEmail,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getStudent = `-- name: GetStudent :one
SELECT s.id, s.class_id, s.full_name, s.birth_date, s.city, s.first_communion, s.confirmation, s.previous_catechism, s.religious_books, s.guardian_father_name, s.guardian_mother_name, s.guardian_phone, s.guardian_email, s.is_active, s.created_at, c.name AS class_name
FROM students s
JOIN classes c ON c.id = s.class_id
WHERE s.id = $1
`

type GetStudentRow struct {
	Student   Student `json:"student"`
	ClassName string  `json:"class_name"`
}

// Detail view: the full student row plus the joined class name. A missing id
// returns no rows (→ 404).
func (q *Queries) GetStudent(ctx context.Context, id pgtype.UUID) (GetStudentRow, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i GetStudentRow
	err := row.Scan(
		&i.Student.ID,
		&i.Student.ClassID,
		&i.Student.FullName,
		&i.Student.BirthDate,
		&i.Student.City,
		&i.Student.FirstCommunion,
		&i.Student.Confirmation,
		&i.Student.PreviousCatechism,
		&i.Student.ReligiousBooks,
		&i.Student.GuardianFatherName,
		&i.Student.GuardianMotherName,
		&i.Student.GuardianPhone,
		&i.Student.GuardianEmail,
		&i.Student.IsActive,
		&i.Student.CreatedAt,
		&i.ClassName,
	)
	return i, err
}

const searchStudents = `-- name: SearchStudents :many
SELECT s.id, s.class_id, s.full_name, s.birth_date, s.city, s.first_communion, s.confirmation, s.previous_catechism, s.religious_books, s.guardian_father_name, s.guardian_mother_name, s.guardian_phone, s.guardian_email, s.is_active, s.created_at, c.name AS class_name
FROM students s
JOIN classes c ON c.id = s.class_id
WHERE $1::text IS NULL
   OR s.full_name ILIKE '%' || $1::text || '%'
ORDER BY s.full_name
`

type SearchStudentsRow struct {
	Student   Student `json:"student"`
	ClassName string  `json:"class_name"`
}

// Coordinator list, optionally filtered by name (ILIKE). The class name is joined
// so the SPA can show it without a second round-trip. A NULL q (no search param)
// returns every student; the same narg is referenced twice so sqlc emits a single
// nullable Q parameter.
func (q *Queries) SearchStudents(ctx context.Context, q_ *string) ([]SearchStudentsRow, error) {
	rows, err := q.db.Query(ctx, searchStudents, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchStudentsRow{}
	for rows.Next() {
		var i SearchStudentsRow
		if err := rows.Scan(
			&i.Student.ID,
			&i.Student.ClassID,
			&i.Student.FullName,
			&i.Student.BirthDate,
			&i.Student.City,
			&i.Student.FirstCommunion,
			&i.Student.Confirmation,
			&i.Student.PreviousCatechism,
			&i.Student.ReligiousBooks,
			&i.Student.GuardianFatherName,
			&i.Student.GuardianMotherName,
			&i.Student.GuardianPhone,
			&i.Student.GuardianEmail,
			&i.Student.IsActive,
			&i.Student.CreatedAt,
			&i.ClassName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students SET
    class_id        = COALESCE($1::uuid, class_id),
    full_name       = COALESCE($2, full_name),
    first_communion = COALESCE($3, first_communion),
    confirmation    = COALESCE($4, confirmation),
    birth_date           = CASE WHEN $5::boolean
                                THEN $6::date ELSE birth_date END,
    city                 = CASE WHEN $7::boolean
                                THEN $8 ELSE city END,
    previous_catechism   = CASE WHEN $9::boolean
                                THEN $10 ELSE previous_catechism END,
    religious_books      = CASE WHEN $11::boolean
                                THEN $12 ELSE religious_books END,
    guardian_father_name = CASE WHEN $13::boolean
                                THEN $14 ELSE guardian_father_name END,
    guardian_mother_name = CASE WHEN $15::boolean
                                THEN $16 ELSE guardian_mother_name END,
    guardian_phone       = CASE WHEN $17::boolean
                                THEN $18 ELSE guardian_phone END,
    guardian_email       = CASE WHEN $19::boolean
                                THEN $20 ELSE guardian_email END
WHERE id = $21
RETURNING id, class_id, full_name, birth_date, city, first_communion, confirmation, previous_catechism, religious_books, guardian_father_name, guardian_mother_name, guardian_phone, guardian_email, is_active, created_at
`

type UpdateStudentParams struct {
	ClassID               pgtype.UUID `json:"class_id"`
	FullName              *string     `json:"full_name"`
	FirstCommunion        *bool       `json:"first_communion"`
	Confirmation          *bool       `json:"confirmation"`
	SetBirthDate          bool        `json:"set_birth_date"`
	BirthDate             pgtype.Date `json:"birth_date"`
	SetCity               bool        `json:"set_city"`
	City                  *string     `json:"city"`
	SetPreviousCatechism  bool        `json:"set_previous_catechism"`
	PreviousCatechism     *string     `json:"previous_catechism"`
	SetReligiousBooks     bool        `json:"set_religious_books"`
	ReligiousBooks        *string     `json:"religious_books"`
	SetGuardianFatherName bool        `json:"set_guardian_father_name"`
	GuardianFatherName    *string     `json:"guardian_father_name"`
	SetGuardianMotherName bool        `json:"set_guardian_mother_name"`
	GuardianMotherName    *string     `json:"guardian_mother_name"`
	SetGuardianPhone      bool        `json:"set_guardian_phone"`
	GuardianPhone         *string     `json:"guardian_phone"`
	SetGuardianEmail      bool        `json:"set_guardian_email"`
	GuardianEmail         *string     `json:"guardian_email"`
	ID                    pgtype.UUID `json:"id"`
}

// Partial update. class_id, full_name and the two booleans fall back to their
// current value when omitted (COALESCE over a NULL narg). The nullable fields are
// tri-state (absent = leave / null = clear / value = set): each is touched only
// when its set_x flag is true, so the caller can clear it to NULL without COALESCE
// swallowing the NULL. Doubles as the row fetch, so a missing id returns no rows
// (→ 404).
func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.ClassID,
		arg.FullName,
		arg.FirstCommunion,
		arg.Confirmation,
		arg.SetBirthDate,
		arg.BirthDate,
		arg.SetCity,
		arg.City,
		arg.SetPreviousCatechism,
		arg.PreviousCatechism,
		arg.SetReligiousBooks,
		arg.ReligiousBooks,
		arg.SetGuardianFatherName,
		arg.GuardianFatherName,
		arg.SetGuardianMotherName,
		arg.GuardianMotherName,
		arg.SetGuardianPhone,
		arg.GuardianPhone,
		arg.SetGuardianEmail,
		arg.GuardianEmail,
		arg.ID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.FullName,
		&i.BirthDate,
		&i.City,
		&i.FirstCommunion,
		&i.Confirmation,
		&i.PreviousCatechism,
		&i.ReligiousBooks,
		&i.GuardianFatherName,
		&i.GuardianMotherName,
		&i.GuardianPhone,
		&i.GuardianEmail,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
