// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSessionsByCatechist = `-- name: CountSessionsByCatechist :one
SELECT count(*) FROM attendance_sessions WHERE catechist_id = $1
`

func (q *Queries) CountSessionsByCatechist(ctx context.Context, catechistID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsByCatechist, catechistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (email, password_hash, full_name, role, must_change_password)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, full_name, role, is_active, must_change_password, created_at
`

type CreateProfileParams struct {
	Email              string `json:"email"`
	PasswordHash       string `json:"password_hash"`
	FullName           string `json:"full_name"`
	Role               string `json:"role"`
	MustChangePassword bool   `json:"must_change_password"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.MustChangePassword,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const getProfileByEmail = `-- name: GetProfileByEmail :one
SELECT id, email, password_hash, full_name, role, is_active, must_change_password, created_at FROM profiles WHERE email = $1
`

func (q *Queries) GetProfileByEmail(ctx context.Context, email string) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByEmail, email)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, email, password_hash, full_name, role, is_active, must_change_password, created_at FROM profiles WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const listCatechists = `-- name: ListCatechists :many
SELECT id, email, password_hash, full_name, role, is_active, must_change_password, created_at FROM profiles WHERE role = 'catechist' ORDER BY full_name
`

func (q *Queries) ListCatechists(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listCatechists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.IsActive,
			&i.MustChangePassword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActive = `-- name: SetActive :exec
UPDATE profiles SET is_active = $2 WHERE id = $1
`

type SetActiveParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) SetActive(ctx context.Context, arg SetActiveParams) error {
	_, err := q.db.Exec(ctx, setActive, arg.ID, arg.IsActive)
	return err
}

const setRole = `-- name: SetRole :exec
UPDATE profiles SET role = $2 WHERE id = $1
`

type SetRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

func (q *Queries) SetRole(ctx context.Context, arg SetRoleParams) error {
	_, err := q.db.Exec(ctx, setRole, arg.ID, arg.Role)
	return err
}

const updateAdminCredentials = `-- name: UpdateAdminCredentials :one
UPDATE profiles
SET password_hash = $2, role = 'admin', is_active = TRUE
WHERE email = $1
RETURNING id, email, password_hash, full_name, role, is_active, must_change_password, created_at
`

type UpdateAdminCredentialsParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateAdminCredentials(ctx context.Context, arg UpdateAdminCredentialsParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateAdminCredentials, arg.Email, arg.PasswordHash)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE profiles
SET password_hash = $2, must_change_password = $3
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID                 pgtype.UUID `json:"id"`
	PasswordHash       string      `json:"password_hash"`
	MustChangePassword bool        `json:"must_change_password"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash, arg.MustChangePassword)
	return err
}
